### PR TITLE
Readme update compiler versions

### PR DESCRIPTION
**Pull request by AlexanderSaydakov**

### CODE REVIEW

**Comment by jmalkin** [comment]
Our CI job used:
  * Mac: `AppleClang 12.0.0.12000032`
  * Ubuntu: `GNU 7.5.0`
  * Windows: `MSVC 19.28.29337.0`

I don't think we've tested on 4.8.5 recently?

**Comment by AlexanderSaydakov** [comment]
Do you think it makes much sense to maintain these versions?

**Comment by jmalkin** [comment]
With the CI job, maybe not. We should probably do a 4.8.5 check occasionally but beyond that I think we can probably just kill this.

**Comment by AlexanderSaydakov** [comment]
I agree, let's just remove this part.

**Review by jmalkin — APPROVED** [review]

**Pull request merged**
